# Generated by Django 4.0.3 on 2022-04-15 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.IntegerField(db_index=True, max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.TextField(max_length=50)),
                ('phoneno', models.IntegerField(db_index=True, max_length=11, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Buyers',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.IntegerField(db_index=True, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('km_driven', models.PositiveBigIntegerField()),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('engine', models.PositiveIntegerField()),
                ('transmission', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(max_length=20)),
                ('seller_type', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=100)),
                ('seats', models.PositiveSmallIntegerField()),
                ('running_cost', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='carimages/')),
                ('slug', models.SlugField(max_length=255)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.IntegerField(db_index=True, max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('seller_type', models.CharField(max_length=30)),
                ('company_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.TextField(max_length=50)),
                ('phoneno', models.IntegerField(db_index=True, max_length=11, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Sellers',
            },
        ),
        migrations.CreateModel(
            name='Wants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('selling_price', models.PositiveIntegerField()),
                ('km_driven', models.PositiveBigIntegerField()),
                ('fuel_type', models.CharField(max_length=20)),
                ('seller_type', models.CharField(max_length=20)),
                ('transmission', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=100)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('engine', models.PositiveIntegerField()),
                ('seats', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('buyer_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.buyer')),
                ('car_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.car')),
            ],
            options={
                'verbose_name_plural': 'Wants',
            },
        ),
    ]
