# Generated by Django 4.0.3 on 2022-04-16 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wants',
            old_name='buyer_id',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='wants',
            old_name='selling_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='wants',
            name='car_id',
        ),
        migrations.AddField(
            model_name='wants',
            name='recommended_car_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='recommended', to='app.car'),
        ),
        migrations.AddField(
            model_name='wants',
            name='wanted_car_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wanted', to='app.car'),
        ),
    ]
