# Generated by Django 4.0.3 on 2022-04-16 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_wants_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wants',
            name='recommended_car_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended', to='app.car'),
        ),
        migrations.AlterField(
            model_name='wants',
            name='wanted_car_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wanted', to='app.car'),
        ),
    ]
