# Generated by Django 4.0.3 on 2022-04-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_wants_recommended_car_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wants',
            name='slug',
        ),
    ]
