# Generated by Django 4.0.3 on 2022-04-16 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_remove_wants_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField(db_index=True, max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('km_driven', models.PositiveBigIntegerField()),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('engine', models.PositiveIntegerField()),
                ('transmission', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(max_length=20)),
                ('seller_type', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=100)),
                ('seats', models.PositiveSmallIntegerField()),
                ('running_cost', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='carimages/')),
                ('score', models.DecimalField(decimal_places=250, max_digits=500)),
                ('buyer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Recommendations',
            },
        ),
    ]
