# Generated by Django 4.0.3 on 2022-04-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendations',
            name='score',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
