# Generated by Django 4.0.3 on 2022-04-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_recommendations_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.IntegerField(db_index=True, max_length=10, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('km_driven', models.PositiveBigIntegerField()),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('engine', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'RecommendationsFeedback',
            },
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
